In [2]:
import numpy as np

creating array


In [3]:
my_list = [1,2,3,4,5]

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

numPy operations 

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(1,2,3)

array([1])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.random.rand(2,2)

array([[0.91500451, 0.51610784],
       [0.34878748, 0.78403158]])